
export default new Map([
["src/content/docs/about.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Fabout.mdx&astroContentModuleFlag=true")],
["src/content/docs/coming-soon.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Fcoming-soon.mdx&astroContentModuleFlag=true")],
["src/content/docs/completed.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Fcompleted.mdx&astroContentModuleFlag=true")],
["src/content/docs/features.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Ffeatures.mdx&astroContentModuleFlag=true")],
["src/content/docs/features/atlassian-administration/atlassian-administration-access-policies-block-mobile-browser-access.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Ffeatures%2Fatlassian-administration%2Fatlassian-administration-access-policies-block-mobile-browser-access.mdx&astroContentModuleFlag=true")],
["src/content/docs/features/atlassian-administration/atlassian-administration-dark-mode-theme-in-atlassian-administration.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Ffeatures%2Fatlassian-administration%2Fatlassian-administration-dark-mode-theme-in-atlassian-administration.mdx&astroContentModuleFlag=true")],
["src/content/docs/features/atlassian-administration/atlassian-administration-scim-api-keys-set-to-expire.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Ffeatures%2Fatlassian-administration%2Fatlassian-administration-scim-api-keys-set-to-expire.mdx&astroContentModuleFlag=true")],
["src/content/docs/features/confluence/confluence-synced-blocks-keep-content-consistent.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Ffeatures%2Fconfluence%2Fconfluence-synced-blocks-keep-content-consistent.mdx&astroContentModuleFlag=true")],
["src/content/docs/features/jira-platform/jira-platform-approvals-are-coming-to-jira.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Ffeatures%2Fjira-platform%2Fjira-platform-approvals-are-coming-to-jira.mdx&astroContentModuleFlag=true")],
["src/content/docs/features/jira-platform/jira-platform-automation-improved-rule-builder-header.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Ffeatures%2Fjira-platform%2Fjira-platform-automation-improved-rule-builder-header.mdx&astroContentModuleFlag=true")],
["src/content/docs/features/jira-platform/jira-platform-jira-plans-drag-and-drop-field-columns.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Ffeatures%2Fjira-platform%2Fjira-platform-jira-plans-drag-and-drop-field-columns.mdx&astroContentModuleFlag=true")],
["src/content/docs/features/rovo/rovo-rovo-responses-now-include-information-from-the-web.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Ffeatures%2Frovo%2Frovo-rovo-responses-now-include-information-from-the-web.mdx&astroContentModuleFlag=true")],
["src/content/docs/index.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Findex.mdx&astroContentModuleFlag=true")],
["src/content/docs/new-this-week.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Fnew-this-week.mdx&astroContentModuleFlag=true")],
["src/content/docs/rolling-out.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Frolling-out.mdx&astroContentModuleFlag=true")]]);
		